alias vimzshrc='vim $HOME/.zshrc && source $_'
alias find_in_python="find ./ -name '*.py' -type f|xargs grep"
alias find_in_java="find ./ -name '*.java' -type f|xargs grep"
alias find_in_go="find ./ -name '*.go' -type f|xargs grep"
alias find_in_js="find ./ -name '*.js*' -type f|xargs grep"
alias vtop="cd $VIM_TOP"
alias ztop="cd $ZSH_TOP"
alias rtop="cd $RC_TOP"
alias top="cd $TOP"
